name: Morgan Digital Ventures
favicon: null
layout_spectrum: 0.7647807921748608
typography_spectrum: 0.39358
title: Morgan Digital Ventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004685'
    - '#0071bc'
    - '#5fa6d4'
    - '#8fc0e1'
    - '#bfdbef'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.7493574160616845
  rhythmicContrast: 0.5
purpose: []
